# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

#
# Below are the different credentials in use within this module
#
#     - member: authenticated member
#     - member_gambling_fr: member with a complex account to gamble in France
#                           not yet verified.
#     - member_gambling_fr_verified: member with a complex account to gamble in France
#                           that has been verified.
#

#
# Default behavior is to protect all actions with member
#

default:
  is_secure: true
  credentials: member

#
# Below are actions that do not require any kind of authentication
#

index:
  is_secure: false

home:
  is_secure: false

search:
  is_secure: false

roomsThumbnailsSearch:
  is_secure: false

roomsThumbnails:
  is_secure: false

roomsThumbnailsHome:
  is_secure: false

view:
  is_secure: false

kupsNews:
  is_secure: false

widgetRanking:
  is_secure: false

widgetKups:
  is_secure: false


widgetKupRanking:
  is_secure: false

getWidgetUrl:
  is_secure: false

roomKupsRanking:
  is_secure: false

roomKupsGeneralRanking:
  is_secure: false

uploadFile:
  is_secure: false

cropFile:
  is_secure: false

changeAvatarsInProd:
  is_secure: false

create:
  is_secure: false

existsRoomName:
  is_secure: false

likePageFansFacebook:
  is_secure: false

# We need to define secure action so that the room custom security filter will be invoked.
# see module/room/config/module.yml for room credentials
kup:
  credentials: [[room_member, room_public_anonymous, room_public_connected]]

kupRules:
  credentials: [[room_member, room_public_anonymous, room_public_connected]]

kupRanking:
  credentials: [[room_member, room_public_anonymous, room_public_connected]]

kupBet:
  is_secure: true
  credentials: room_member

kupResults:
  is_secure: true
  credentials: room_member

edit:
  is_secure: true
  credentials: room_administrator

delete:
  is_secure: true
  credentials: room_administrator

kups:
  is_secure: true
  credentials: room_administrator

members:
  is_secure: true
  credentials: room_administrator

invite:
  is_secure: true
  credentials: room_member
