# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# Home module configuration
all:
  security_sofun:
    administrator: Administrator
    member: Member
  payline:
      payment_currency: 978
      payment_action: 101
      payment_mode: CPT
      cancel_url: https://www.betkup.fr
      notification_url: https://www.betkup.fr
      return_url: https://www.betkup.fr
      custom_payment_template_url: ''
      custom_payment_page_code: ''
      contract_number: 1234567
      contract_number_list: ''
      primary_call_timeout: 15
      secondary_call_timeout: 15
      primary_max_fail_retry: 1 
      secondary_max_fail_retry: 2
      primary_replay_timer: 15
      secondary_replay_timer: 15
      payline_err_code: 02101,02102,02103
      payline_ws_switch_enable: ''
      payline_switch_back_timer: 600
      merchant_id: 12156100549557
      access_key: 4CxFvOvxzUQ73AFut4AJ
      production_flag: FALSE # SWITCH TO TRUE ON PRODUCTION INSTANCE ONLY
      transaction_status_unknown: UNKNOWN
      transaction_status_pending: PENDING
      transaction_status_refused: REFUSED
      transaction_status_approved: APPROVED
  credit:
    min: 5
    max: 1000
    wire_min: 5
  registration:
    simple_age: 16
    advanced_age: 18
    black_countries: [DE, US, GB]
    account_type_simple: SIMPLE
    account_type_gambling_fr: GAMBLING_FR
    account_type_gambling_fr_verified: VERIFIED_FR
    account_status_created: CREATED
    account_status_confirmed: CONFIRMED
  limit:
    min_weekly_credit: 5
    min_weekly_bets: 5
    weekly_credit: 20000
    weekly_bets: 10000
    automatic_wire: 10
  birthdate_cookie_prefix: free_betkup_birthdate_   
  legigame:
    mailto: none # CHANGEME
    mailcc: none # CHANGEME
    mailfrom: verification@betkup.com 