# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

#
# Below are the different credentials in use within this module
#
#     - member: authenticated member
#     - member_gambling_fr: member with a complex account to gamble in France 
#                           not yet verified.
#     - member_gambling_fr_verified: member with a complex account to gamble in France 
#                           that has been verified.
#

#
# Default behavior is to protect all actions with member
#

default:
  is_secure: true
  credentials: member

#
# Action that require a gambling account
# 

credit:
  is_secure: true
  credentials: member_gambling_fr

registerCredit:
  is_secure: true
  credentials: member_gambling_fr

#
# Action that require a gambling account
# 

wire:
  is_secure: true
  credentials: member_gambling_fr_verified
  
#
# Below are actions that do not require any kind of authentication
#

register:
  is_secure: false

registerAdvanced:
  is_secure: false
  
login:
  is_secure: false

loginFacebook:
  is_secure: false

passwordForgotten:
  is_secure: false

passwordReset:
  is_secure: false
  
searchCity:
  is_secure: false
  
existsNickname:
  is_secure: false